temp_dir = "/tmp/pg-auto-backup" # Temporary directory for backup files
cron = "0 0 * * * *"             # Cron expression for backup schedule
log_level = "INFO"               # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)

[storage]
# Storage type (Local, S3)
type = "Local"

# The directory where the backup files will be stored
# When using the Local storage type
path = "/var/lib/pg-auto-backup"

# S3 Access key
## access_key = ""

# S3 Secret key
## access_secret = ""

# S3 Endpoint
## endpoint = ""

# S3 Region
## region = ""

# S3 Bucket
## bucket = ""

# S3 Enforce path style
# Enable this option for MinIO and other S3-compatible services
## enforce_path_style = false

[connection]
# Database host
host = "localhost"

# Database port
port = 5432

# Database user
# Note that the user must have the necessary permissions to perform the backup
user = "postgres"

# Database user password
password = "password"

[pg_dump]
# Path to pg_dump binary
binary_path = "/usr/bin/pg_dump"

# Format of the backup (Plain, Custom, Tar)
#   Can be overridden by database specific settings
# Note that the directory type is not supported
# --format={} option in pg_dump
format = "Plain"

# Section to include in the backup (PreData, Data, PostData)
# --section={} option in pg_dump
sections = ["PreData", "Data", "PostData"]

# Whether to create the database before restoring
#   Can be omitted
#   Can be overridden by database specific settings
# --create option in pg_dump
## create = false

# Whether to drop the database before restoring
#   Can be omitted
#   Can be overridden by database specific settings
# --clean option in pg_dump
## clean = false

# Do not save the corresponding data
#   Can be omitted
#   Can be overridden by database specific settings
# Available values:
#   LargeObjects, Owner, Privileges, Comments,
#   Publications, SecurityLabels, Subscriptions,
#   TableAccessMethod, Tablespace, ToastCompression,
#   UnloggedTableData
# --no-{} option in pg_dump
## do_not_save = []

# Disable something
#   Can be omitted
#   Can be overridden by database specific settings
# Available values:
#   DollarQuoting, Triggers
# --disable={} option in pg_dump
## disable = []

# Extra arguments for pg_dump
#   Can be omitted
#   Can be overridden by database specific settings
## extra_args = []

# Backup multiple databases by duplicating
# the [[databases]] section
[[databases]]
# Database name
name = "my_database"

# Format of the backup (Plain, Custom, Tar)
#   Can be omitted
#   Will override the pg_dump.format option
# Note that the directory type is not supported
# --format={} option in pg_dump
## format = "Plain"

# Tables to include in the backup, empty for all
#   Can be omitted
# --table={} option in pg_dump
## include_tables = []

# Tables to exclude from the backup
#   Can be omitted
# --exclude-table={} option in pg_dump
## exclude_tables = []

# Schemas to include in the backup, empty for all
#   Can be omitted
# --schema={} option in pg_dump
## include_schema = []

# Schemas to exclude from the backup
#   Can be omitted
# --exclude-schema={} option in pg_dump
## exclude_schema = []

# Section to include in the backup (PreData, Data, PostData)
#   Can be omitted
#   Will override the pg_dump.sections option
# --section={} option in pg_dump
## sections = ["PreData", "Data", "PostData"]

# Whether to create the database before restoring
#   Can be omitted
#   Will override the pg_dump.create option
# --create option in pg_dump
## create = false

# Whether to drop the database before restoring
#   Can be omitted
#   Will override the pg_dump.clean option
# --clean option in pg_dump
## clean = false

# Do not save the corresponding data
#   Can be omitted
#   Will override the pg_dump.do_not_save option
# Available values:
#   LargeObjects, Owner, Privileges, Comments,
#   Publications, SecurityLabels, Subscriptions,
#   TableAccessMethod, Tablespace, ToastCompression,
#   UnloggedTableData
# --no-{} option in pg_dump
## do_not_save = []

# Disable something
#   Can be omitted
#   Will override the pg_dump.disable option
# Available values:
#   DollarQuoting, Triggers
# --disable={} option in pg_dump
## disable = []

# Extra arguments for pg_dump
#   Can be omitted
#   Will override the pg_dump.extra_args option
## extra_args = []
