[storage]
type = "Azure"

# Azure Storage Account name
account = ""

# Azure Storage Account access key
access_key = ""

# Azure Blob Container name
container = ""

# Azure Blob Path in the container
#   Can be omitted for the root of the container
# Do not include the leading and trailing slashes
#   OK: path = "my/path"
#   NG: path = "/my/path/"
## path = ""
