name: "Build image and upload to ghcr.io"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: "Docker: Setup Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Docker: Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: "Docker: Metadata"
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/LiamSho/pg-auto-backup
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=pr
            type=sha

      - name: "Docker: Build and Push Image"
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
